// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsISxejgxIqhrBopkaYvHd8ZsEepeGkc4',
    appId: '1:699399167394:web:9e48c7597e2558c4c9e6fb',
    messagingSenderId: '699399167394',
    projectId: 'fish-tank-5b754',
    authDomain: 'fish-tank-5b754.firebaseapp.com',
    storageBucket: 'fish-tank-5b754.firebasestorage.app',
    measurementId: 'G-BPJZ24PC2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgRHzUtWW0QOkscUHcA3YsDixweUr238',
    appId: '1:699399167394:android:0ff2d0ef4839693bc9e6fb',
    messagingSenderId: '699399167394',
    projectId: 'fish-tank-5b754',
    storageBucket: 'fish-tank-5b754.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJPQ0uxp81bIZHCxKjK7fxe9dknm6WMQ',
    appId: '1:699399167394:ios:b1f1f53da3cbfbaec9e6fb',
    messagingSenderId: '699399167394',
    projectId: 'fish-tank-5b754',
    storageBucket: 'fish-tank-5b754.firebasestorage.app',
    iosBundleId: 'com.example.rswFleetManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSJPQ0uxp81bIZHCxKjK7fxe9dknm6WMQ',
    appId: '1:699399167394:ios:b1f1f53da3cbfbaec9e6fb',
    messagingSenderId: '699399167394',
    projectId: 'fish-tank-5b754',
    storageBucket: 'fish-tank-5b754.firebasestorage.app',
    iosBundleId: 'com.example.rswFleetManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsISxejgxIqhrBopkaYvHd8ZsEepeGkc4',
    appId: '1:699399167394:web:5d143bc76f4d10cbc9e6fb',
    messagingSenderId: '699399167394',
    projectId: 'fish-tank-5b754',
    authDomain: 'fish-tank-5b754.firebaseapp.com',
    storageBucket: 'fish-tank-5b754.firebasestorage.app',
    measurementId: 'G-D2S1YMMYNW',
  );

}